package com.cells.parts.subnetproxy;

import java.util.Optional;
import java.util.UUID;

import javax.annotation.Nonnull;

import net.minecraft.entity.player.EntityPlayer;

import appeng.api.networking.IGrid;
import appeng.api.networking.security.IActionHost;
import appeng.api.networking.security.IActionSource;


/**
 * Custom {@link IActionSource} used by subnet proxies to mark forwarded
 * delta events with three pieces of metadata:
 * <ul>
 *   <li>The forwarding {@link PartSubnetProxyFront} (so other proxies can
 *       distinguish proxy-forwarded changes from real machine sources)</li>
 *   <li>A stable {@link UUID} event identifier carried unchanged through
 *       a forwarding chain, used by per-grid coordinators to dedup the
 *       same logical event arriving via multiple paths (diamond topology)</li>
 *   <li>The {@link IGrid} where the change <em>originally</em> happened,
 *       used for loop-back rejection (don't forward back to source-grid),
 *       election routing (only one front per origin publishes), and
 *       reach-set checks (only forward if origin is in the proxy's
 *       exposed-origins set, enforcing the 1-hop visibility rule).</li>
 * </ul>
 * <p>
 * <b>UUID lifetime:</b> generated by the FIRST forwarding hop (when a local
 * change originates), and preserved verbatim through all subsequent hops.
 * Coordinator dedup uses an LRU set; UUIDs are not persisted.
 */
public final class SubnetProxyEventSource implements IActionSource {

    private final Optional<IActionHost> machineOpt;
    private final UUID eventId;
    private final IGrid originGrid;

    public SubnetProxyEventSource(IActionHost forwardingFront, UUID eventId, IGrid originGrid) {
        this.machineOpt = Optional.ofNullable(forwardingFront);
        this.eventId = eventId;
        this.originGrid = originGrid;
    }

    @Nonnull
    @Override
    public Optional<EntityPlayer> player() {
        return Optional.empty();
    }

    @Nonnull
    @Override
    public Optional<IActionHost> machine() {
        return machineOpt;
    }

    @Nonnull
    @Override
    public <T> Optional<T> context(@Nonnull Class<T> key) {
        // No contexts attached. AE2 currently has no public context types.
        return Optional.empty();
    }

    public UUID eventId() {
        return eventId;
    }

    public IGrid originGrid() {
        return originGrid;
    }

    /**
     * Extract the event UUID from a source if it's a SubnetProxyEventSource,
     * else null. Used by listeners to reuse the same UUID through a chain.
     */
    public static UUID extractEventId(IActionSource source) {
        if (source instanceof SubnetProxyEventSource) return ((SubnetProxyEventSource) source).eventId;
        return null;
    }

    /**
     * Extract the origin-grid from a source if it's a SubnetProxyEventSource,
     * else null. Callers should fall back to deriving origin from
     * {@code source.machine().getActionableNode().getGrid()}.
     */
    public static IGrid extractOriginGrid(IActionSource source) {
        if (source instanceof SubnetProxyEventSource) return ((SubnetProxyEventSource) source).originGrid;
        return null;
    }
}
